
{% set name = "sage" %}
{% set version = "7.5.1" %}
{% set sage_root = "/root/sage" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 0
  script:
    - python {{ sage_root }}/conda_build_script.py {{ sage_root }} {{ name }}
    - mkdir -p "${PREFIX}/etc/conda/activate.d"
    - mkdir -p "${PREFIX}/etc/conda/deactivate.d"
    - cp "${RECIPE_DIR}/activate.sh" "${PREFIX}/etc/conda/activate.d/sage_activate.sh"
    - cp "${RECIPE_DIR}/deactivate.sh" "${PREFIX}/etc/conda/deactivate.d/sage_deactivate.sh"

  features:
    - blas_openblas

requirements:
  run:
    - alabaster  
    - appnope  
    - arb  
    - babel  
    - backports_abc  
    - backports_shutil_get_terminal_size  
    - backports_ssl_match_hostname  
    - boost_cropped  
    - brial  
    - bzip2  
    - cddlib  
    - cephes  
    - certifi  
    - cliquer  
    - combinatorial_designs  
    - configparser  
    - conway_polynomials  
    - cvxopt  
    - cycler  
    - cysignals  
    - cython  
    - dateutil  
    - decorator  
    - docutils  
    - ecl  
    - eclib  
    - ecm  
    - elliptic_curves  
    - entrypoints  
    - fflas_ffpack  
    - flask  
    - flask_autoindex  
    - flask_babel  
    - flask_oldsessions  
    - flask_openid  
    - flask_silk  
    - flint  
    - flintqs  
    - fpylll  
    - freetype  
    - functools32  
    - future  
    - gap  
    - gc  
    - gcc  
    - gf2x  
    - gfan  
    - giac  
    - git  
    - givaro  
    - glpk  
    - graphs  
    - gsl  
    - iconv  
    - imagesize  
    - iml  
    - ipykernel  
    - ipython  
    - ipython_genutils  
    - ipywidgets  
    - itsdangerous  
    - jinja2  
    - jmol  
    - jsonschema  
    - jupyter_client  
    - jupyter_core  
    - lcalc  
    - libfplll  
    - libgap  
    - libgd  
    - libpng  
    - linbox  
    - lrcalc  
    - m4ri  
    - m4rie  
    - markupsafe  
    - mathjax  
    - matplotlib  
    - maxima  
    - mistune  
    - mpc  
    - mpfi  
    - mpfr  
    - mpmath  
    - nauty  
    - nbconvert  
    - nbformat  
    - ncurses  
    - networkx  
    - notebook  
    - ntl  
    - numpy  
    - openblas  
    - palp  
    - pari  
    - pari_galdata  
    - pari_seadata_small  
    - patch  
    - pathlib2  
    - pathpy  
    - pexpect  
    - pickleshare  
    - pillow  
    - pip  
    - pkgconf  
    - pkgconfig  
    - planarity  
    - polytopes_db  
    - ppl  
    - prompt_toolkit  
    - psutil  
    - ptyprocess  
    - pycrypto  
    - pygments  
    - pynac  
    - pyparsing  
    - python_openid  
    - pytz  
    - pyzmq  
    - r  
    - ratpoints  
    - readline  
    - rpy2  
    - rubiks  
    - rw  
    - sagenb  
    - sagenb_export  
    - sagetex  
    - scipy  
    - setuptools  
    - setuptools_scm  
    - simplegeneric  
    - singledispatch  
    - singular  
    - six  
    - snowballstemmer  
    - speaklater  
    - sphinx  
    - sqlite  
    - symmetrica  
    - sympow  
    - sympy  
    - tachyon  
    - terminado  
    - thebe  
    - tornado  
    - traitlets  
    - twisted  
    - vcversioner  
    - wcwidth  
    - werkzeug  
    - widgetsnbextension  
    - zeromq  
    - zlib  
    - zn_poly  
    - zope_interface 
    - arb 
    - blas 1.1 openblas 
    - openblas 0.2.19|0.2.19.* 
    - brial 
    - cephes 
    - cliquer 
    - cysignals 
    - ecl 
    - eclib 
    - ecm 
    - flint 
    - libgd 
    - givaro 
    - glpk 
    - gsl 
    - iml 
    - jinja2 
    - jupyter_core 
    - lcalc 
    - lrcalc 
    - libgap 
    - libpng >=1.6.28,<1.7 
    - linbox 
    - m4ri 
    - m4rie 
    - mpc 
    - mpfi 
    - mpfr 
    - gmp 
    - ntl 
    - numpy 1.11.* 
    - pari 
    - planarity 
    - ppl 
    - pynac 
    - python 
    - ratpoints 
    - readline 6.2* 
    - rw 
    - singular 
    - six 
    - symmetrica 
    - zn_poly 
    - sagelib 
    - ipython 
    - pexpect 
    - psutil 
    - sageruntime 
    - sagelib 



about:
  description: |
    {{ name }} packaged for sagemath. Download sage-spkg-sources for the source
